version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    command: ["npm", "run", "start"]
    volumes:
      - .:/app

